"""
generate_examples.py - Generate synthetic XRD .xy pattern files for testing.

Creates 3 example patterns with Gaussian peaks and noise.
"""
from __future__ import annotations

import numpy as np
from pathlib import Path

def gaussian(x, center, height, fwhm):
    """Gaussian peak."""
    sigma = fwhm / (2 * np.sqrt(2 * np.log(2)))
    return height * np.exp(-0.5 * ((x - center) / sigma) ** 2)

def generate_pattern(
    x_range=(10, 80),
    step=0.02,
    peaks=None,
    background_params=None,
    noise_level=20,
    seed=None,
):
    if seed is not None:
        np.random.seed(seed)
    x = np.arange(x_range[0], x_range[1] + step, step)
    y = np.zeros_like(x, dtype=float)

    # Background: linear + polynomial
    if background_params is None:
        background_params = {"slope": 0.5, "intercept": 100, "curv": 0.0}
    bg = (
        background_params.get("intercept", 100)
        + background_params.get("slope", 0) * (x - x[0]) * 0.1
        + background_params.get("curv", 0) * (x - x.mean()) ** 2 * 0.001
    )
    y += bg

    if peaks:
        for center, height, fwhm in peaks:
            y += gaussian(x, center, height, fwhm)

    # Add noise
    noise = np.random.normal(0, noise_level, size=x.shape)
    y += noise
    y = np.maximum(y, 0)  # clip negative

    return x, y

def save_xy(path, x, y):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(f"# Synthetic XRD pattern generated by generate_examples.py\n")
        f.write(f"# File: {path.name}\n")
        f.write(f"# Columns: 2theta  intensity\n")
        for xi, yi in zip(x, y):
            f.write(f"{xi:.4f}\t{yi:.2f}\n")
    print(f"Saved {path}")

def main():
    out_dir = Path(__file__).parent / "example_data"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Pattern A: e.g., cubic phase peaks at 28.4, 32-33, 47, 56
    peaks_A = [
        (28.44, 15000, 0.25),
        (32.2, 8000, 0.3),
        (33.0, 2000, 0.35),
        (47.4, 9000, 0.35),
        (56.4, 6000, 0.4),
        (19.5, 1200, 0.5),
        (62.5, 3000, 0.45),
    ]
    x, y = generate_pattern(
        x_range=(10, 70),
        step=0.02,
        peaks=peaks_A,
        background_params={"slope": 2, "intercept": 200, "curv": 0.02},
        noise_level=30,
        seed=42,
    )
    save_xy(out_dir / "synthetic_cubic.xy", x, y)

    # Pattern B: slightly shifted / different relative intensities (tetragonal)
    peaks_B = [
        (25.3, 5000, 0.3),
        (28.0, 8000, 0.28),
        (30.1, 12000, 0.26),
        (32.5, 4000, 0.32),
        (38.2, 3000, 0.35),
        (48.0, 7000, 0.38),
        (50.5, 5500, 0.4),
        (59.8, 2500, 0.45),
    ]
    x, y = generate_pattern(
        x_range=(10, 70),
        step=0.02,
        peaks=peaks_B,
        background_params={"slope": 1.5, "intercept": 180, "curv": 0.015},
        noise_level=28,
        seed=123,
    )
    save_xy(out_dir / "synthetic_tetragonal.xy", x, y)

    # Pattern C: broad peaks, amorphous + crystalline
    peaks_C = [
        (20.5, 3000, 0.8),
        (26.7, 9000, 0.5),
        (35.2, 6000, 0.6),
        (44.8, 4000, 0.7),
        (52.0, 2000, 1.0),
    ]
    x, y = generate_pattern(
        x_range=(10, 70),
        step=0.02,
        peaks=peaks_C,
        background_params={"slope": 5, "intercept": 300, "curv": 0.05},
        noise_level=35,
        seed=999,
    )
    # Add broad amorphous hump
    y += gaussian(x, 22.0, 2000, 5.0)
    save_xy(out_dir / "synthetic_amorphous_mix.xy", x, y)

    print(f"\nGenerated 3 synthetic patterns in {out_dir.resolve()}")

if __name__ == "__main__":
    main()
